# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fngr < Formula
  desc "Command-line journal for logging events with FTS, tags, and trees."
  homepage "https://github.com/monolithiclab/fngr"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/monolithiclab/fngr/releases/download/v0.0.1/fngr_0.0.1_darwin_amd64.tar.gz"
      sha256 "cd869bf465ce63fbbdb8c7b68055df0ce830fc6bd40cd73db9caad5e31475e30"

      define_method(:install) do
        bin.install "fngr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/monolithiclab/fngr/releases/download/v0.0.1/fngr_0.0.1_darwin_arm64.tar.gz"
      sha256 "216bad436d4ce0524eb3d31be0750c4c6dbb96c150d838f233698f473e7d1153"

      define_method(:install) do
        bin.install "fngr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/monolithiclab/fngr/releases/download/v0.0.1/fngr_0.0.1_linux_amd64.tar.gz"
      sha256 "dfdaaedf94f299de98522ae675bbfd9e1c5cc0e1453f3ac315f0d93ed6c14747"
      define_method(:install) do
        bin.install "fngr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/monolithiclab/fngr/releases/download/v0.0.1/fngr_0.0.1_linux_arm64.tar.gz"
      sha256 "baf4d04ee0a4e1e4dcb27cd2ea6412e01961d5c9cd96c2923ad12335e740d9ca"
      define_method(:install) do
        bin.install "fngr"
      end
    end
  end

  test do
    assert_match "fngr", shell_output("#{bin}/fngr --version")
  end
end
